#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export GAZEBO_MODEL_PATH="$SCRIPT_DIR:$SCRIPT_DIR/aruco_models:$GAZEBO_MODEL_PATH"
export GAZEBO_MODEL_PATH="$SCRIPT_DIR:$SCRIPT_DIR/models:$GAZEBO_MODEL_PATH"

export GAZEBO_RESOURCE_PATH="$SCRIPT_DIR:$SCRIPT_DIR/textures:$GAZEBO_RESOURCE_PATH"

export GAZEBO_PLUGIN_PATH="$SCRIPT_DIR:$SCRIPT_DIR/plugins:$GAZEBO_PLUGIN_PATH"

export ROS_PACKAGE_PATH="$SCRIPT_DIR:$SCRIPT_DIR/my_clover_description:$ROS_PACKAGE_PATH"